/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.chatproject.view;

import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import com.chatproject.controller.LoginHandler;
import com.chatproject.controller.LookAndFeelManager;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author hungl
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    public static String REPO_LINK = "https://github.com/Gawasna/Chatproject";
    public static String ISSUE_LINK = "https://github.com/Gawasna/Chatproject/issues/";
    public String Resources_File_Path = "src\\main\\java\\com\\chatproject\\info\\resources.txt";
    public static String DEFAULT_LAF = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
    
    public Login() {
        initComponents();
        LookAndFeelManager.registerFrame(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jDialog2 = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userfield = new PlaceholderTextField("Tên đăng nhập");
        passwordfield = new PlaceholderPasswordField("Mật khẩu");
        forgotPassBtn = new javax.swing.JButton();
        LoginBtn = new javax.swing.JButton();
        registerBtn = new javax.swing.JButton();
        guestLogBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        motiflaf = new javax.swing.JMenuItem();
        nimbuslaf = new javax.swing.JMenuItem();
        windowlaf = new javax.swing.JMenuItem();
        winclassiclaf = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        githubBtn = new javax.swing.JMenuItem();
        resBtn = new javax.swing.JMenuItem();
        issuesBtn = new javax.swing.JMenuItem();

        jDialog1.setTitle("Resources");
        jDialog1.setBounds(new java.awt.Rectangle(0, 0, 400, 600));
        jDialog1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialog1.setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton5.setText("jButton5");

        jTextField2.setText("jTextField2");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(65, 65, 65))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 2, 18)); // NOI18N
        jLabel1.setText("Chat application...");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMinimumSize(new java.awt.Dimension(4000, 2048));
        jLabel1.setPreferredSize(new java.awt.Dimension(4000, 2048));

        userfield.setText("");
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });

        forgotPassBtn.setText("Quên mật khẩu ?");
        forgotPassBtn.setBorder(null);
        forgotPassBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        forgotPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPassBtnActionPerformed(evt);
            }
        });

        LoginBtn.setText("Đăng nhập");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });

        registerBtn.setText("Tạo tài khoản mới");
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        guestLogBtn.setText("Đăng nhập khách");
        guestLogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestLogBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("hoặc");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userfield)
                    .addComponent(passwordfield)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(forgotPassBtn)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addComponent(LoginBtn))
                    .addComponent(registerBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(guestLogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(userfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LoginBtn)
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(forgotPassBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(registerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guestLogBtn)
                .addContainerGap())
        );

        jMenu1.setText("Theme");

        motiflaf.setText("Motif");
        motiflaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motiflafActionPerformed(evt);
            }
        });
        jMenu1.add(motiflaf);

        nimbuslaf.setText("Nimbus");
        nimbuslaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimbuslafActionPerformed(evt);
            }
        });
        jMenu1.add(nimbuslaf);

        windowlaf.setText("Window");
        windowlaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowlafActionPerformed(evt);
            }
        });
        jMenu1.add(windowlaf);

        winclassiclaf.setText("Window Classic");
        winclassiclaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winclassiclafActionPerformed(evt);
            }
        });
        jMenu1.add(winclassiclaf);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");

        githubBtn.setText("Github");
        githubBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                githubBtnActionPerformed(evt);
            }
        });
        jMenu2.add(githubBtn);

        resBtn.setText("Resources");
        resBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resBtnActionPerformed(evt);
            }
        });
        jMenu2.add(resBtn);

        issuesBtn.setText("Issues");
        issuesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuesBtnActionPerformed(evt);
            }
        });
        jMenu2.add(issuesBtn);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void OpenRepoLink (String LINK) {
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(new URI(LINK));
            } catch (Exception e) {
            }
        } else {
            System.out.println("Desktop is not supported.");
        }
    }
    
    private void githubBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_githubBtnActionPerformed
        OpenRepoLink(REPO_LINK);
    }//GEN-LAST:event_githubBtnActionPerformed
    
    private void ReadResourcesInProject() {
    try {
        File file = new File(Resources_File_Path);
        try (FileReader fileReader = new FileReader(file); BufferedReader bufferedReader = new BufferedReader(fileReader)) {
            String line;
            StringBuilder stringBuilder = new StringBuilder();
            while ((line = bufferedReader.readLine()) != null) {
                stringBuilder.append(line).append("\n");
            }
           
            jTextArea1.setText(stringBuilder.toString());
            jTextArea1.setCaretPosition(0); // Đặt vị trí con trỏ ở đầu văn bản
            jTextArea1.setLineWrap(true); // Tự động xuống dòng khi cần
        }
    } catch (IOException e) {
        jTextArea1.setText("Error reading file: " + e.getMessage());
    }
}

    private void resBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resBtnActionPerformed
        jDialog1.setVisible(true);
        ReadResourcesInProject();
    }//GEN-LAST:event_resBtnActionPerformed
    
    //NonFunction() = tính năng chưa làm
    private void guestLogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestLogBtnActionPerformed
       LoginHandler.NonFunction();
       LoginHandler.GuestLogin();
       //chạy func lấy tên để gen rồi mới chạy frame
       new MainChat().setVisible(true);
    }//GEN-LAST:event_guestLogBtnActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here:
    String username = userfield.getText();
    String password = passwordfield.getText();

    // Kiểm tra cú pháp đăng nhập
     if (LoginHandler.checkLoginSyntax(username, password)) {
        if (LoginHandler.checkAccountInDatabase(username, password)) {
            //tiến hành đăng nhập
            //mở cửa sổ MainChat
            System.out.println("Đăng nhập thành công");
        } else {
            System.out.println("Tài khoản không tồn tại hoặc mật khẩu không đúng");
        }
    } else {
        System.out.println("Lỗi");
    }
        //kiểm tra cú pháp đăng nhập và tài khoản , hợp lệ thì thực hiện
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void forgotPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPassBtnActionPerformed
        LoginHandler.NonFunction();
    }//GEN-LAST:event_forgotPassBtnActionPerformed

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void motiflafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motiflafActionPerformed
        // TODO add your handling code here:
        changeLookAndFeel(LookAndFeelManager.DEFAULT_LAF);
        
    }//GEN-LAST:event_motiflafActionPerformed

    private void nimbuslafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimbuslafActionPerformed
        // TODO add your handling code here:
        changeLookAndFeel(LookAndFeelManager.NIMBUS_LAF);
    }//GEN-LAST:event_nimbuslafActionPerformed

    private void windowlafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowlafActionPerformed
        // TODO add your handling code here:
        changeLookAndFeel(LookAndFeelManager.WINDOW_LAF);
    }//GEN-LAST:event_windowlafActionPerformed

    private void winclassiclafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winclassiclafActionPerformed
        // TODO add your handling code here:
        changeLookAndFeel(LookAndFeelManager.WINDOW_CLASSIC_LAF);
    }//GEN-LAST:event_winclassiclafActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
    }//GEN-LAST:event_registerBtnActionPerformed

    private void issuesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuesBtnActionPerformed
        // TODO add your handling code here:'
        OpenRepoLink(ISSUE_LINK);
    }//GEN-LAST:event_issuesBtnActionPerformed
    
    private void changeLookAndFeel(String lookAndFeel) {
        try {
            LookAndFeelManager.changeLookAndFeelForAllFrames(lookAndFeel);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
        UIManager.setLookAndFeel(DEFAULT_LAF);
}       catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
}
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn;
    private javax.swing.JButton forgotPassBtn;
    private javax.swing.JMenuItem githubBtn;
    private javax.swing.JButton guestLogBtn;
    private javax.swing.JMenuItem issuesBtn;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JMenuItem motiflaf;
    private javax.swing.JMenuItem nimbuslaf;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JButton registerBtn;
    private javax.swing.JMenuItem resBtn;
    private javax.swing.JTextField userfield;
    private javax.swing.JMenuItem winclassiclaf;
    private javax.swing.JMenuItem windowlaf;
    // End of variables declaration//GEN-END:variables
}
